// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: pkg/structures/device-model-registry/devicemodelregistry.proto

package devicemodelregistry

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,json=model-name,proto3" json:"Name,omitempty"`
	YangFiles     []*YangFile            `protobuf:"bytes,2,rep,name=YangFiles,json=yang-files,proto3" json:"YangFiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceModel) Reset() {
	*x = DeviceModel{}
	mi := &file_pkg_structures_device_model_registry_devicemodelregistry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceModel) ProtoMessage() {}

func (x *DeviceModel) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_structures_device_model_registry_devicemodelregistry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceModel.ProtoReflect.Descriptor instead.
func (*DeviceModel) Descriptor() ([]byte, []int) {
	return file_pkg_structures_device_model_registry_devicemodelregistry_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeviceModel) GetYangFiles() []*YangFile {
	if x != nil {
		return x.YangFiles
	}
	return nil
}

type YangFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,json=file-name,proto3" json:"Name,omitempty"`
	Revision      string                 `protobuf:"bytes,2,opt,name=Revision,json=file-revision,proto3" json:"Revision,omitempty"`
	Structure     string                 `protobuf:"bytes,3,opt,name=Structure,json=structure,proto3" json:"Structure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YangFile) Reset() {
	*x = YangFile{}
	mi := &file_pkg_structures_device_model_registry_devicemodelregistry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YangFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YangFile) ProtoMessage() {}

func (x *YangFile) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_structures_device_model_registry_devicemodelregistry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YangFile.ProtoReflect.Descriptor instead.
func (*YangFile) Descriptor() ([]byte, []int) {
	return file_pkg_structures_device_model_registry_devicemodelregistry_proto_rawDescGZIP(), []int{1}
}

func (x *YangFile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *YangFile) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *YangFile) GetStructure() string {
	if x != nil {
		return x.Structure
	}
	return ""
}

var File_pkg_structures_device_model_registry_devicemodelregistry_proto protoreflect.FileDescriptor

var file_pkg_structures_device_model_registry_devicemodelregistry_proto_rawDesc = string([]byte{
	0x0a, 0x3e, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73,
	0x2f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2d, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2d, 0x72, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x13, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x72, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x72, 0x79, 0x22, 0x65, 0x0a, 0x0b, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x12, 0x18, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2d, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x3c,
	0x0a, 0x09, 0x59, 0x61, 0x6e, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1d, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x72,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2e, 0x59, 0x61, 0x6e, 0x67, 0x46, 0x69, 0x6c, 0x65,
	0x52, 0x0a, 0x79, 0x61, 0x6e, 0x67, 0x2d, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x22, 0x62, 0x0a, 0x08,
	0x59, 0x61, 0x6e, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x17, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x2d, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1f, 0x0a, 0x08, 0x52, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x66, 0x69, 0x6c, 0x65, 0x2d, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65,
	0x42, 0x17, 0x5a, 0x15, 0x2e, 0x2f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
})

var (
	file_pkg_structures_device_model_registry_devicemodelregistry_proto_rawDescOnce sync.Once
	file_pkg_structures_device_model_registry_devicemodelregistry_proto_rawDescData []byte
)

func file_pkg_structures_device_model_registry_devicemodelregistry_proto_rawDescGZIP() []byte {
	file_pkg_structures_device_model_registry_devicemodelregistry_proto_rawDescOnce.Do(func() {
		file_pkg_structures_device_model_registry_devicemodelregistry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_structures_device_model_registry_devicemodelregistry_proto_rawDesc), len(file_pkg_structures_device_model_registry_devicemodelregistry_proto_rawDesc)))
	})
	return file_pkg_structures_device_model_registry_devicemodelregistry_proto_rawDescData
}

var file_pkg_structures_device_model_registry_devicemodelregistry_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_structures_device_model_registry_devicemodelregistry_proto_goTypes = []any{
	(*DeviceModel)(nil), // 0: devicemodelregistry.DeviceModel
	(*YangFile)(nil),    // 1: devicemodelregistry.YangFile
}
var file_pkg_structures_device_model_registry_devicemodelregistry_proto_depIdxs = []int32{
	1, // 0: devicemodelregistry.DeviceModel.YangFiles:type_name -> devicemodelregistry.YangFile
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_structures_device_model_registry_devicemodelregistry_proto_init() }
func file_pkg_structures_device_model_registry_devicemodelregistry_proto_init() {
	if File_pkg_structures_device_model_registry_devicemodelregistry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_structures_device_model_registry_devicemodelregistry_proto_rawDesc), len(file_pkg_structures_device_model_registry_devicemodelregistry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_structures_device_model_registry_devicemodelregistry_proto_goTypes,
		DependencyIndexes: file_pkg_structures_device_model_registry_devicemodelregistry_proto_depIdxs,
		MessageInfos:      file_pkg_structures_device_model_registry_devicemodelregistry_proto_msgTypes,
	}.Build()
	File_pkg_structures_device_model_registry_devicemodelregistry_proto = out.File
	file_pkg_structures_device_model_registry_devicemodelregistry_proto_goTypes = nil
	file_pkg_structures_device_model_registry_devicemodelregistry_proto_depIdxs = nil
}
