// Code generated by protoc-gen-go. DO NOT EDIT.
// source: adapterResponse.proto

package adapterResponse

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AdapterResponse struct {
	Entries              []*SchemaEntry `protobuf:"bytes,1,rep,name=Entries,proto3" json:"Entries,omitempty"`
	Timestamp            int64          `protobuf:"varint,2,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AdapterResponse) Reset()         { *m = AdapterResponse{} }
func (m *AdapterResponse) String() string { return proto.CompactTextString(m) }
func (*AdapterResponse) ProtoMessage()    {}
func (*AdapterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_81d3828b016b0905, []int{0}
}

func (m *AdapterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdapterResponse.Unmarshal(m, b)
}
func (m *AdapterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdapterResponse.Marshal(b, m, deterministic)
}
func (m *AdapterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdapterResponse.Merge(m, src)
}
func (m *AdapterResponse) XXX_Size() int {
	return xxx_messageInfo_AdapterResponse.Size(m)
}
func (m *AdapterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AdapterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AdapterResponse proto.InternalMessageInfo

func (m *AdapterResponse) GetEntries() []*SchemaEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *AdapterResponse) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type SchemaEntry struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Tag                  string   `protobuf:"bytes,2,opt,name=Tag,proto3" json:"Tag,omitempty"`
	Namespace            string   `protobuf:"bytes,3,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
	Value                string   `protobuf:"bytes,4,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SchemaEntry) Reset()         { *m = SchemaEntry{} }
func (m *SchemaEntry) String() string { return proto.CompactTextString(m) }
func (*SchemaEntry) ProtoMessage()    {}
func (*SchemaEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_81d3828b016b0905, []int{1}
}

func (m *SchemaEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchemaEntry.Unmarshal(m, b)
}
func (m *SchemaEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchemaEntry.Marshal(b, m, deterministic)
}
func (m *SchemaEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchemaEntry.Merge(m, src)
}
func (m *SchemaEntry) XXX_Size() int {
	return xxx_messageInfo_SchemaEntry.Size(m)
}
func (m *SchemaEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_SchemaEntry.DiscardUnknown(m)
}

var xxx_messageInfo_SchemaEntry proto.InternalMessageInfo

func (m *SchemaEntry) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SchemaEntry) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *SchemaEntry) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *SchemaEntry) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*AdapterResponse)(nil), "adapterResponse.AdapterResponse")
	proto.RegisterType((*SchemaEntry)(nil), "adapterResponse.SchemaEntry")
}

func init() { proto.RegisterFile("adapterResponse.proto", fileDescriptor_81d3828b016b0905) }

var fileDescriptor_81d3828b016b0905 = []byte{
	// 192 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4d, 0x4c, 0x49, 0x2c,
	0x28, 0x49, 0x2d, 0x0a, 0x4a, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0xe2, 0x47, 0x13, 0x56, 0x4a, 0xe7, 0xe2, 0x77, 0x44, 0x15, 0x12, 0x32, 0xe3, 0x62,
	0x77, 0xcd, 0x2b, 0x29, 0xca, 0x4c, 0x2d, 0x96, 0x60, 0x54, 0x60, 0xd6, 0xe0, 0x36, 0x92, 0xd1,
	0x43, 0x37, 0x2c, 0x38, 0x39, 0x23, 0x35, 0x37, 0x11, 0xa4, 0xaa, 0x32, 0x08, 0xa6, 0x58, 0x48,
	0x86, 0x8b, 0x33, 0x24, 0x33, 0x37, 0xb5, 0xb8, 0x24, 0x31, 0xb7, 0x40, 0x82, 0x49, 0x81, 0x51,
	0x83, 0x39, 0x08, 0x21, 0xa0, 0x94, 0xce, 0xc5, 0x8d, 0xa4, 0x4b, 0x48, 0x88, 0x8b, 0xc5, 0x2f,
	0x31, 0x37, 0x55, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0xcc, 0x16, 0x12, 0xe0, 0x62, 0x0e,
	0x49, 0x4c, 0x07, 0x6b, 0xe5, 0x0c, 0x02, 0x31, 0x41, 0x46, 0x82, 0x64, 0x8a, 0x0b, 0x12, 0x93,
	0x53, 0x25, 0x98, 0xc1, 0xe2, 0x08, 0x01, 0x21, 0x11, 0x2e, 0xd6, 0xb0, 0xc4, 0x9c, 0xd2, 0x54,
	0x09, 0x16, 0xb0, 0x0c, 0x84, 0xe3, 0x24, 0x14, 0x25, 0xa0, 0x8f, 0xe6, 0xde, 0x24, 0x36, 0xb0,
	0xef, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf4, 0x9f, 0xe2, 0x4d, 0x16, 0x01, 0x00, 0x00,
}
