// Code generated by protoc-gen-go. DO NOT EDIT.
// source: notification.proto

package notification

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Region CalcConfig
type UUID struct {
	Value                string   `protobuf:"bytes,1,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UUID) Reset()         { *m = UUID{} }
func (m *UUID) String() string { return proto.CompactTextString(m) }
func (*UUID) ProtoMessage()    {}
func (*UUID) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{0}
}

func (m *UUID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UUID.Unmarshal(m, b)
}
func (m *UUID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UUID.Marshal(b, m, deterministic)
}
func (m *UUID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UUID.Merge(m, src)
}
func (m *UUID) XXX_Size() int {
	return xxx_messageInfo_UUID.Size(m)
}
func (m *UUID) XXX_DiscardUnknown() {
	xxx_messageInfo_UUID.DiscardUnknown(m)
}

var xxx_messageInfo_UUID proto.InternalMessageInfo

func (m *UUID) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type IdList struct {
	Values               []*UUID  `protobuf:"bytes,1,rep,name=Values,proto3" json:"Values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdList) Reset()         { *m = IdList{} }
func (m *IdList) String() string { return proto.CompactTextString(m) }
func (*IdList) ProtoMessage()    {}
func (*IdList) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{1}
}

func (m *IdList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdList.Unmarshal(m, b)
}
func (m *IdList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdList.Marshal(b, m, deterministic)
}
func (m *IdList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdList.Merge(m, src)
}
func (m *IdList) XXX_Size() int {
	return xxx_messageInfo_IdList.Size(m)
}
func (m *IdList) XXX_DiscardUnknown() {
	xxx_messageInfo_IdList.DiscardUnknown(m)
}

var xxx_messageInfo_IdList proto.InternalMessageInfo

func (m *IdList) GetValues() []*UUID {
	if m != nil {
		return m.Values
	}
	return nil
}

// Region MSTP
type InMstpCistPortTableRequest struct {
	PathCost             int32    `protobuf:"varint,1,opt,name=PathCost,proto3" json:"PathCost,omitempty"`
	EdgePort             bool     `protobuf:"varint,2,opt,name=EdgePort,proto3" json:"EdgePort,omitempty"`
	MacEnabled           bool     `protobuf:"varint,3,opt,name=MacEnabled,proto3" json:"MacEnabled,omitempty"`
	RestrictedRole       bool     `protobuf:"varint,4,opt,name=RestrictedRole,proto3" json:"RestrictedRole,omitempty"`
	RestrictedTcn        bool     `protobuf:"varint,5,opt,name=RestrictedTcn,proto3" json:"RestrictedTcn,omitempty"`
	ProtocolMigration    bool     `protobuf:"varint,6,opt,name=ProtocolMigration,proto3" json:"ProtocolMigration,omitempty"`
	EnableBPDURx         bool     `protobuf:"varint,7,opt,name=EnableBPDURx,proto3" json:"EnableBPDURx,omitempty"`
	EnableBPDUTx         bool     `protobuf:"varint,8,opt,name=EnableBPDUTx,proto3" json:"EnableBPDUTx,omitempty"`
	PseudoRootId         []byte   `protobuf:"bytes,9,opt,name=PseudoRootId,proto3" json:"PseudoRootId,omitempty"`
	IsL2Gp               bool     `protobuf:"varint,10,opt,name=IsL2Gp,proto3" json:"IsL2Gp,omitempty"`
	Port                 uint32   `protobuf:"varint,11,opt,name=Port,proto3" json:"Port,omitempty"`
	ComponentID          uint32   `protobuf:"varint,12,opt,name=ComponentID,proto3" json:"ComponentID,omitempty"`
	DeviceIP             string   `protobuf:"bytes,13,opt,name=DeviceIP,proto3" json:"DeviceIP,omitempty"`
	KVGetter             bool     `protobuf:"varint,14,opt,name=KVGetter,proto3" json:"KVGetter,omitempty"`
	CSSetter             bool     `protobuf:"varint,15,opt,name=CSSetter,proto3" json:"CSSetter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InMstpCistPortTableRequest) Reset()         { *m = InMstpCistPortTableRequest{} }
func (m *InMstpCistPortTableRequest) String() string { return proto.CompactTextString(m) }
func (*InMstpCistPortTableRequest) ProtoMessage()    {}
func (*InMstpCistPortTableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{2}
}

func (m *InMstpCistPortTableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InMstpCistPortTableRequest.Unmarshal(m, b)
}
func (m *InMstpCistPortTableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InMstpCistPortTableRequest.Marshal(b, m, deterministic)
}
func (m *InMstpCistPortTableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InMstpCistPortTableRequest.Merge(m, src)
}
func (m *InMstpCistPortTableRequest) XXX_Size() int {
	return xxx_messageInfo_InMstpCistPortTableRequest.Size(m)
}
func (m *InMstpCistPortTableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InMstpCistPortTableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InMstpCistPortTableRequest proto.InternalMessageInfo

func (m *InMstpCistPortTableRequest) GetPathCost() int32 {
	if m != nil {
		return m.PathCost
	}
	return 0
}

func (m *InMstpCistPortTableRequest) GetEdgePort() bool {
	if m != nil {
		return m.EdgePort
	}
	return false
}

func (m *InMstpCistPortTableRequest) GetMacEnabled() bool {
	if m != nil {
		return m.MacEnabled
	}
	return false
}

func (m *InMstpCistPortTableRequest) GetRestrictedRole() bool {
	if m != nil {
		return m.RestrictedRole
	}
	return false
}

func (m *InMstpCistPortTableRequest) GetRestrictedTcn() bool {
	if m != nil {
		return m.RestrictedTcn
	}
	return false
}

func (m *InMstpCistPortTableRequest) GetProtocolMigration() bool {
	if m != nil {
		return m.ProtocolMigration
	}
	return false
}

func (m *InMstpCistPortTableRequest) GetEnableBPDURx() bool {
	if m != nil {
		return m.EnableBPDURx
	}
	return false
}

func (m *InMstpCistPortTableRequest) GetEnableBPDUTx() bool {
	if m != nil {
		return m.EnableBPDUTx
	}
	return false
}

func (m *InMstpCistPortTableRequest) GetPseudoRootId() []byte {
	if m != nil {
		return m.PseudoRootId
	}
	return nil
}

func (m *InMstpCistPortTableRequest) GetIsL2Gp() bool {
	if m != nil {
		return m.IsL2Gp
	}
	return false
}

func (m *InMstpCistPortTableRequest) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *InMstpCistPortTableRequest) GetComponentID() uint32 {
	if m != nil {
		return m.ComponentID
	}
	return 0
}

func (m *InMstpCistPortTableRequest) GetDeviceIP() string {
	if m != nil {
		return m.DeviceIP
	}
	return ""
}

func (m *InMstpCistPortTableRequest) GetKVGetter() bool {
	if m != nil {
		return m.KVGetter
	}
	return false
}

func (m *InMstpCistPortTableRequest) GetCSSetter() bool {
	if m != nil {
		return m.CSSetter
	}
	return false
}

type InMstpCistTableRequest struct {
	MaxHops              int32    `protobuf:"varint,1,opt,name=MaxHops,proto3" json:"MaxHops,omitempty"`
	ComponentID          uint32   `protobuf:"varint,2,opt,name=ComponentID,proto3" json:"ComponentID,omitempty"`
	DeviceIP             string   `protobuf:"bytes,3,opt,name=DeviceIP,proto3" json:"DeviceIP,omitempty"`
	KVGetter             bool     `protobuf:"varint,4,opt,name=KVGetter,proto3" json:"KVGetter,omitempty"`
	CSSetter             bool     `protobuf:"varint,5,opt,name=CSSetter,proto3" json:"CSSetter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InMstpCistTableRequest) Reset()         { *m = InMstpCistTableRequest{} }
func (m *InMstpCistTableRequest) String() string { return proto.CompactTextString(m) }
func (*InMstpCistTableRequest) ProtoMessage()    {}
func (*InMstpCistTableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{3}
}

func (m *InMstpCistTableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InMstpCistTableRequest.Unmarshal(m, b)
}
func (m *InMstpCistTableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InMstpCistTableRequest.Marshal(b, m, deterministic)
}
func (m *InMstpCistTableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InMstpCistTableRequest.Merge(m, src)
}
func (m *InMstpCistTableRequest) XXX_Size() int {
	return xxx_messageInfo_InMstpCistTableRequest.Size(m)
}
func (m *InMstpCistTableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InMstpCistTableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InMstpCistTableRequest proto.InternalMessageInfo

func (m *InMstpCistTableRequest) GetMaxHops() int32 {
	if m != nil {
		return m.MaxHops
	}
	return 0
}

func (m *InMstpCistTableRequest) GetComponentID() uint32 {
	if m != nil {
		return m.ComponentID
	}
	return 0
}

func (m *InMstpCistTableRequest) GetDeviceIP() string {
	if m != nil {
		return m.DeviceIP
	}
	return ""
}

func (m *InMstpCistTableRequest) GetKVGetter() bool {
	if m != nil {
		return m.KVGetter
	}
	return false
}

func (m *InMstpCistTableRequest) GetCSSetter() bool {
	if m != nil {
		return m.CSSetter
	}
	return false
}

type InMstpConfigTableRequest struct {
	FormatSelector       int32    `protobuf:"varint,1,opt,name=FormatSelector,proto3" json:"FormatSelector,omitempty"`
	ConfigurationName    string   `protobuf:"bytes,2,opt,name=ConfigurationName,proto3" json:"ConfigurationName,omitempty"`
	RevisionLevel        uint32   `protobuf:"varint,3,opt,name=RevisionLevel,proto3" json:"RevisionLevel,omitempty"`
	ComponentID          uint32   `protobuf:"varint,4,opt,name=ComponentID,proto3" json:"ComponentID,omitempty"`
	DeviceIP             string   `protobuf:"bytes,5,opt,name=DeviceIP,proto3" json:"DeviceIP,omitempty"`
	KVGetter             bool     `protobuf:"varint,6,opt,name=KVGetter,proto3" json:"KVGetter,omitempty"`
	CSSetter             bool     `protobuf:"varint,7,opt,name=CSSetter,proto3" json:"CSSetter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InMstpConfigTableRequest) Reset()         { *m = InMstpConfigTableRequest{} }
func (m *InMstpConfigTableRequest) String() string { return proto.CompactTextString(m) }
func (*InMstpConfigTableRequest) ProtoMessage()    {}
func (*InMstpConfigTableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{4}
}

func (m *InMstpConfigTableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InMstpConfigTableRequest.Unmarshal(m, b)
}
func (m *InMstpConfigTableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InMstpConfigTableRequest.Marshal(b, m, deterministic)
}
func (m *InMstpConfigTableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InMstpConfigTableRequest.Merge(m, src)
}
func (m *InMstpConfigTableRequest) XXX_Size() int {
	return xxx_messageInfo_InMstpConfigTableRequest.Size(m)
}
func (m *InMstpConfigTableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InMstpConfigTableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InMstpConfigTableRequest proto.InternalMessageInfo

func (m *InMstpConfigTableRequest) GetFormatSelector() int32 {
	if m != nil {
		return m.FormatSelector
	}
	return 0
}

func (m *InMstpConfigTableRequest) GetConfigurationName() string {
	if m != nil {
		return m.ConfigurationName
	}
	return ""
}

func (m *InMstpConfigTableRequest) GetRevisionLevel() uint32 {
	if m != nil {
		return m.RevisionLevel
	}
	return 0
}

func (m *InMstpConfigTableRequest) GetComponentID() uint32 {
	if m != nil {
		return m.ComponentID
	}
	return 0
}

func (m *InMstpConfigTableRequest) GetDeviceIP() string {
	if m != nil {
		return m.DeviceIP
	}
	return ""
}

func (m *InMstpConfigTableRequest) GetKVGetter() bool {
	if m != nil {
		return m.KVGetter
	}
	return false
}

func (m *InMstpConfigTableRequest) GetCSSetter() bool {
	if m != nil {
		return m.CSSetter
	}
	return false
}

type InMstpFidToMstiV2TableRequest struct {
	Fid                  uint32   `protobuf:"varint,1,opt,name=fid,proto3" json:"fid,omitempty"`
	ComponentID          uint32   `protobuf:"varint,2,opt,name=ComponentID,proto3" json:"ComponentID,omitempty"`
	DeviceIP             string   `protobuf:"bytes,3,opt,name=DeviceIP,proto3" json:"DeviceIP,omitempty"`
	KVGetter             bool     `protobuf:"varint,4,opt,name=KVGetter,proto3" json:"KVGetter,omitempty"`
	CSSetter             bool     `protobuf:"varint,5,opt,name=CSSetter,proto3" json:"CSSetter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InMstpFidToMstiV2TableRequest) Reset()         { *m = InMstpFidToMstiV2TableRequest{} }
func (m *InMstpFidToMstiV2TableRequest) String() string { return proto.CompactTextString(m) }
func (*InMstpFidToMstiV2TableRequest) ProtoMessage()    {}
func (*InMstpFidToMstiV2TableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{5}
}

func (m *InMstpFidToMstiV2TableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InMstpFidToMstiV2TableRequest.Unmarshal(m, b)
}
func (m *InMstpFidToMstiV2TableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InMstpFidToMstiV2TableRequest.Marshal(b, m, deterministic)
}
func (m *InMstpFidToMstiV2TableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InMstpFidToMstiV2TableRequest.Merge(m, src)
}
func (m *InMstpFidToMstiV2TableRequest) XXX_Size() int {
	return xxx_messageInfo_InMstpFidToMstiV2TableRequest.Size(m)
}
func (m *InMstpFidToMstiV2TableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InMstpFidToMstiV2TableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InMstpFidToMstiV2TableRequest proto.InternalMessageInfo

func (m *InMstpFidToMstiV2TableRequest) GetFid() uint32 {
	if m != nil {
		return m.Fid
	}
	return 0
}

func (m *InMstpFidToMstiV2TableRequest) GetComponentID() uint32 {
	if m != nil {
		return m.ComponentID
	}
	return 0
}

func (m *InMstpFidToMstiV2TableRequest) GetDeviceIP() string {
	if m != nil {
		return m.DeviceIP
	}
	return ""
}

func (m *InMstpFidToMstiV2TableRequest) GetKVGetter() bool {
	if m != nil {
		return m.KVGetter
	}
	return false
}

func (m *InMstpFidToMstiV2TableRequest) GetCSSetter() bool {
	if m != nil {
		return m.CSSetter
	}
	return false
}

type InMstpPortTableRequest struct {
	Priority             int32    `protobuf:"varint,1,opt,name=Priority,proto3" json:"Priority,omitempty"`
	PathCost             int32    `protobuf:"varint,2,opt,name=PathCost,proto3" json:"PathCost,omitempty"`
	ComponentID          uint32   `protobuf:"varint,3,opt,name=ComponentID,proto3" json:"ComponentID,omitempty"`
	Port                 uint32   `protobuf:"varint,4,opt,name=Port,proto3" json:"Port,omitempty"`
	MstID                uint32   `protobuf:"varint,5,opt,name=MstID,proto3" json:"MstID,omitempty"`
	DeviceIP             string   `protobuf:"bytes,6,opt,name=DeviceIP,proto3" json:"DeviceIP,omitempty"`
	KVGetter             bool     `protobuf:"varint,7,opt,name=KVGetter,proto3" json:"KVGetter,omitempty"`
	CSSetter             bool     `protobuf:"varint,8,opt,name=CSSetter,proto3" json:"CSSetter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InMstpPortTableRequest) Reset()         { *m = InMstpPortTableRequest{} }
func (m *InMstpPortTableRequest) String() string { return proto.CompactTextString(m) }
func (*InMstpPortTableRequest) ProtoMessage()    {}
func (*InMstpPortTableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{6}
}

func (m *InMstpPortTableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InMstpPortTableRequest.Unmarshal(m, b)
}
func (m *InMstpPortTableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InMstpPortTableRequest.Marshal(b, m, deterministic)
}
func (m *InMstpPortTableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InMstpPortTableRequest.Merge(m, src)
}
func (m *InMstpPortTableRequest) XXX_Size() int {
	return xxx_messageInfo_InMstpPortTableRequest.Size(m)
}
func (m *InMstpPortTableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InMstpPortTableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InMstpPortTableRequest proto.InternalMessageInfo

func (m *InMstpPortTableRequest) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *InMstpPortTableRequest) GetPathCost() int32 {
	if m != nil {
		return m.PathCost
	}
	return 0
}

func (m *InMstpPortTableRequest) GetComponentID() uint32 {
	if m != nil {
		return m.ComponentID
	}
	return 0
}

func (m *InMstpPortTableRequest) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *InMstpPortTableRequest) GetMstID() uint32 {
	if m != nil {
		return m.MstID
	}
	return 0
}

func (m *InMstpPortTableRequest) GetDeviceIP() string {
	if m != nil {
		return m.DeviceIP
	}
	return ""
}

func (m *InMstpPortTableRequest) GetKVGetter() bool {
	if m != nil {
		return m.KVGetter
	}
	return false
}

func (m *InMstpPortTableRequest) GetCSSetter() bool {
	if m != nil {
		return m.CSSetter
	}
	return false
}

type InMstpTableRequest struct {
	BridgePriority       int32    `protobuf:"varint,1,opt,name=BridgePriority,proto3" json:"BridgePriority,omitempty"`
	ComponentID          uint32   `protobuf:"varint,2,opt,name=ComponentID,proto3" json:"ComponentID,omitempty"`
	MstpID               int32    `protobuf:"varint,3,opt,name=MstpID,proto3" json:"MstpID,omitempty"`
	DeviceIP             string   `protobuf:"bytes,4,opt,name=DeviceIP,proto3" json:"DeviceIP,omitempty"`
	KVGetter             bool     `protobuf:"varint,5,opt,name=KVGetter,proto3" json:"KVGetter,omitempty"`
	CSSetter             bool     `protobuf:"varint,6,opt,name=CSSetter,proto3" json:"CSSetter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InMstpTableRequest) Reset()         { *m = InMstpTableRequest{} }
func (m *InMstpTableRequest) String() string { return proto.CompactTextString(m) }
func (*InMstpTableRequest) ProtoMessage()    {}
func (*InMstpTableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{7}
}

func (m *InMstpTableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InMstpTableRequest.Unmarshal(m, b)
}
func (m *InMstpTableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InMstpTableRequest.Marshal(b, m, deterministic)
}
func (m *InMstpTableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InMstpTableRequest.Merge(m, src)
}
func (m *InMstpTableRequest) XXX_Size() int {
	return xxx_messageInfo_InMstpTableRequest.Size(m)
}
func (m *InMstpTableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InMstpTableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InMstpTableRequest proto.InternalMessageInfo

func (m *InMstpTableRequest) GetBridgePriority() int32 {
	if m != nil {
		return m.BridgePriority
	}
	return 0
}

func (m *InMstpTableRequest) GetComponentID() uint32 {
	if m != nil {
		return m.ComponentID
	}
	return 0
}

func (m *InMstpTableRequest) GetMstpID() int32 {
	if m != nil {
		return m.MstpID
	}
	return 0
}

func (m *InMstpTableRequest) GetDeviceIP() string {
	if m != nil {
		return m.DeviceIP
	}
	return ""
}

func (m *InMstpTableRequest) GetKVGetter() bool {
	if m != nil {
		return m.KVGetter
	}
	return false
}

func (m *InMstpTableRequest) GetCSSetter() bool {
	if m != nil {
		return m.CSSetter
	}
	return false
}

func init() {
	proto.RegisterType((*UUID)(nil), "notification.UUID")
	proto.RegisterType((*IdList)(nil), "notification.IdList")
	proto.RegisterType((*InMstpCistPortTableRequest)(nil), "notification.InMstpCistPortTableRequest")
	proto.RegisterType((*InMstpCistTableRequest)(nil), "notification.InMstpCistTableRequest")
	proto.RegisterType((*InMstpConfigTableRequest)(nil), "notification.InMstpConfigTableRequest")
	proto.RegisterType((*InMstpFidToMstiV2TableRequest)(nil), "notification.InMstpFidToMstiV2TableRequest")
	proto.RegisterType((*InMstpPortTableRequest)(nil), "notification.InMstpPortTableRequest")
	proto.RegisterType((*InMstpTableRequest)(nil), "notification.InMstpTableRequest")
}

func init() {
	proto.RegisterFile("notification.proto", fileDescriptor_736a457d4a5efa07)
}

var fileDescriptor_736a457d4a5efa07 = []byte{
	// 778 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x55, 0x5f, 0x6f, 0xda, 0x48,
	0x10, 0x8f, 0x01, 0x1b, 0x32, 0x81, 0xe4, 0x6e, 0x95, 0x43, 0x7b, 0xe4, 0x72, 0xb2, 0x50, 0x14,
	0xa1, 0xbb, 0x13, 0x91, 0xb8, 0x7b, 0xb8, 0xe7, 0x40, 0x92, 0xa2, 0x86, 0x08, 0x19, 0xc8, 0x43,
	0xfb, 0x50, 0x39, 0xf6, 0x42, 0x57, 0x32, 0x5e, 0x6a, 0x2f, 0x51, 0xf2, 0x0d, 0xfa, 0xd0, 0xef,
	0xd1, 0x7e, 0x96, 0x7e, 0x9a, 0x7e, 0x82, 0xaa, 0xf2, 0xae, 0xf9, 0xb3, 0x0b, 0xb1, 0x92, 0xa7,
	0xbe, 0x79, 0xfe, 0x78, 0x66, 0x7e, 0xbf, 0x99, 0x9d, 0x01, 0x14, 0x32, 0x4e, 0xc7, 0xd4, 0x73,
	0x39, 0x65, 0x61, 0x73, 0x16, 0x31, 0xce, 0x50, 0x79, 0x5d, 0x57, 0x3b, 0x9a, 0x30, 0x36, 0x09,
	0xc8, 0x99, 0xb0, 0xdd, 0xcd, 0xc7, 0x67, 0x64, 0x3a, 0xe3, 0x8f, 0xd2, 0xb5, 0xfe, 0x07, 0x14,
	0x46, 0xa3, 0x6e, 0x07, 0x1d, 0x82, 0x79, 0xeb, 0x06, 0x73, 0x82, 0x0d, 0xdb, 0x68, 0xec, 0x3a,
	0x52, 0xa8, 0xff, 0x07, 0x56, 0xd7, 0xbf, 0xa6, 0x31, 0x47, 0x7f, 0x81, 0x25, 0x54, 0x31, 0x36,
	0xec, 0x7c, 0x63, 0xaf, 0x85, 0x9a, 0x4a, 0xde, 0x24, 0x86, 0x93, 0x7a, 0xd4, 0xbf, 0xe7, 0xa1,
	0xd6, 0x0d, 0x7b, 0x31, 0x9f, 0xb5, 0x69, 0xcc, 0xfb, 0x2c, 0xe2, 0x43, 0xf7, 0x2e, 0x20, 0x0e,
	0xf9, 0x30, 0x27, 0x31, 0x47, 0x35, 0x28, 0xf5, 0x5d, 0xfe, 0xbe, 0xcd, 0x62, 0x2e, 0xb2, 0x99,
	0xce, 0x52, 0x4e, 0x6c, 0x17, 0xfe, 0x84, 0x24, 0xff, 0xe0, 0x9c, 0x6d, 0x34, 0x4a, 0xce, 0x52,
	0x46, 0x7f, 0x02, 0xf4, 0x5c, 0xef, 0x22, 0x4c, 0x62, 0xf9, 0x38, 0x2f, 0xac, 0x6b, 0x1a, 0x74,
	0x0a, 0xfb, 0x0e, 0x89, 0x79, 0x44, 0x3d, 0x4e, 0x7c, 0x87, 0x05, 0x04, 0x17, 0x84, 0x8f, 0xa6,
	0x45, 0x27, 0x50, 0x59, 0x69, 0x86, 0x5e, 0x88, 0x4d, 0xe1, 0xa6, 0x2a, 0xd1, 0x3f, 0xf0, 0x6b,
	0x3f, 0x61, 0xc8, 0x63, 0x41, 0x8f, 0x4e, 0x22, 0x01, 0x13, 0x5b, 0xc2, 0x73, 0xd3, 0x80, 0xea,
	0x50, 0x96, 0x65, 0x9c, 0xf7, 0x3b, 0x23, 0xe7, 0x01, 0x17, 0x85, 0xa3, 0xa2, 0x53, 0x7d, 0x86,
	0x0f, 0xb8, 0xa4, 0xfb, 0x0c, 0x85, 0x4f, 0x3f, 0x26, 0x73, 0x9f, 0x39, 0x8c, 0xf1, 0xae, 0x8f,
	0x77, 0x6d, 0xa3, 0x51, 0x76, 0x14, 0x1d, 0xaa, 0x82, 0xd5, 0x8d, 0xaf, 0x5b, 0x57, 0x33, 0x0c,
	0x22, 0x42, 0x2a, 0x21, 0x04, 0x05, 0xc1, 0xdb, 0x9e, 0x6d, 0x34, 0x2a, 0x8e, 0xf8, 0x46, 0x36,
	0xec, 0xb5, 0xd9, 0x74, 0xc6, 0x42, 0x12, 0xf2, 0x6e, 0x07, 0x97, 0x85, 0x69, 0x5d, 0x95, 0x30,
	0xde, 0x21, 0xf7, 0xd4, 0x23, 0xdd, 0x3e, 0xae, 0x88, 0xde, 0x2f, 0xe5, 0xc4, 0xf6, 0xfa, 0xf6,
	0x8a, 0x70, 0x4e, 0x22, 0xbc, 0x2f, 0xbb, 0xb1, 0x90, 0x13, 0x5b, 0x7b, 0x30, 0x90, 0xb6, 0x03,
	0x69, 0x5b, 0xc8, 0xf5, 0x2f, 0x06, 0x54, 0x57, 0x03, 0xa0, 0x34, 0x1f, 0x43, 0xb1, 0xe7, 0x3e,
	0xbc, 0x62, 0xb3, 0x38, 0xed, 0xfd, 0x42, 0xd4, 0x4b, 0xcd, 0x65, 0x97, 0x9a, 0xcf, 0x28, 0xb5,
	0x90, 0x51, 0xaa, 0xa9, 0x95, 0xfa, 0x29, 0x07, 0x38, 0x2d, 0x95, 0x85, 0x63, 0x3a, 0x51, 0x8a,
	0x3d, 0x85, 0xfd, 0x4b, 0x16, 0x4d, 0x5d, 0x3e, 0x20, 0x01, 0xf1, 0x38, 0x8b, 0xd2, 0x9a, 0x35,
	0x6d, 0x32, 0x2b, 0xf2, 0xef, 0xb9, 0x1c, 0x87, 0x1b, 0x77, 0x4a, 0x04, 0x80, 0x5d, 0x67, 0xd3,
	0x20, 0xe7, 0xef, 0x9e, 0xc6, 0x94, 0x85, 0xd7, 0xe4, 0x9e, 0x04, 0x02, 0x4b, 0xc5, 0x51, 0x95,
	0x3a, 0x1d, 0x85, 0x6c, 0x3a, 0xcc, 0x0c, 0x3a, 0xac, 0x0c, 0x3a, 0x8a, 0x1a, 0x1d, 0x9f, 0x0d,
	0x38, 0x96, 0x74, 0x5c, 0x52, 0x7f, 0xc8, 0x7a, 0x31, 0xa7, 0xb7, 0x2d, 0x85, 0x93, 0x5f, 0x20,
	0x3f, 0xa6, 0xbe, 0x20, 0xa2, 0xe2, 0x24, 0x9f, 0x3f, 0xa9, 0x71, 0xdf, 0x96, 0x33, 0xb6, 0x75,
	0xc1, 0x44, 0x94, 0x45, 0x94, 0x3f, 0x2e, 0x17, 0x4c, 0x2a, 0x2b, 0xcb, 0x27, 0xa7, 0x2d, 0x1f,
	0x0d, 0x48, 0x7e, 0x13, 0xc8, 0xe2, 0x89, 0x15, 0xd6, 0x9e, 0xd8, 0x21, 0x98, 0xbd, 0x38, 0xf1,
	0x37, 0x85, 0x52, 0x0a, 0x0a, 0x64, 0x2b, 0x03, 0x72, 0x31, 0x03, 0x72, 0x49, 0x83, 0xfc, 0xd5,
	0x00, 0x24, 0x21, 0xeb, 0x53, 0x7a, 0x1e, 0xd1, 0x64, 0x4b, 0xaa, 0xa0, 0x35, 0xed, 0x33, 0xfa,
	0x54, 0x05, 0x2b, 0x89, 0x9e, 0x62, 0x37, 0x9d, 0x54, 0x52, 0xc0, 0x14, 0x32, 0xc0, 0x98, 0x19,
	0x60, 0x2c, 0x15, 0x4c, 0xeb, 0xa3, 0x09, 0xe5, 0x9b, 0xb5, 0x13, 0x82, 0xfe, 0x07, 0x68, 0xbb,
	0x81, 0x27, 0xdf, 0x0b, 0x3a, 0x54, 0xef, 0x8b, 0xbc, 0x42, 0xb5, 0x2d, 0x57, 0xa7, 0xbe, 0x83,
	0x3c, 0x38, 0x1e, 0xcd, 0x7c, 0x97, 0x13, 0xf9, 0xef, 0xc6, 0xe1, 0x41, 0x0d, 0x2d, 0xd8, 0x93,
	0xb7, 0xa9, 0x56, 0x6d, 0xca, 0x63, 0xd9, 0x5c, 0x1c, 0xcb, 0xe6, 0x45, 0x72, 0x2c, 0xeb, 0x3b,
	0xe8, 0x2d, 0xfc, 0xbe, 0x2d, 0x89, 0x4c, 0x70, 0xf2, 0x54, 0x82, 0x67, 0x06, 0x7f, 0x07, 0x47,
	0x1b, 0xc1, 0x57, 0xeb, 0x08, 0x9d, 0x6e, 0x0d, 0xbf, 0xb1, 0xaf, 0x32, 0x12, 0x50, 0xb0, 0xf5,
	0x04, 0xfa, 0x03, 0x47, 0x7f, 0x6f, 0xcb, 0xf2, 0xc4, 0x1a, 0x78, 0x19, 0x51, 0xab, 0x4e, 0x6c,
	0x25, 0xea, 0x05, 0x5d, 0x18, 0xc0, 0x6f, 0x7a, 0x70, 0x19, 0xd8, 0xde, 0x16, 0xf8, 0x79, 0x41,
	0xcf, 0x0f, 0xde, 0x54, 0xce, 0xd6, 0xff, 0xbe, 0xb3, 0x84, 0xcb, 0xbf, 0x3f, 0x02, 0x00, 0x00,
	0xff, 0xff, 0xb6, 0xbf, 0x66, 0x65, 0x5c, 0x09, 0x00, 0x00,
}
